### ISSUE TITLE
Visit lectures in first weeks and present/recruit Code@LTH

### ISSUE THREAD

**Issue by ErikBjare** [Code-at-LTH/meta#10]
- [x] Figure out which lectures to visit
   + [x] D1 in E:A 14:15 the 17th of September
   + [x] F1 in Ma:7 16:00 the 17th of September
 - [x] Write a summary of what to say

**Comment by exoji2e** [comment]
"{vad vi heter}. Vi kommer från Code@LTH, en studentförening som försöker få fler studenter att programmera mer på fritiden. För att åstadkomma detta arrangerar vi events, så som inspirationsföreläsningar, programmeringstävlingar och workshops.

Nu på onsdag ska vi ha vårt första event för hösten: 'Introduktion till python och viktiga idéer i programmering'. Detta event riktar sig till er som precis börjat på LTH!

På torsdag nästa vecka kommer jag att hålla en inspirationsföreläsning om tävlingsprogrammering. Om 3 veckor är det nämligen dags för den årliga programmeringstävlingen NCPC. Så kom på min föreläsning för att få lite tips inför tävlingen, och för mer information om hur tävlingen går till.

För mer information, besök vår facebook-sida: https://facebook.com/codeatlth

Båda dessa event kommer vara i E:B, klockan 17 på onsdag, och 17 på torsdag nästa vecka. Vi ses där!"
